apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "apollo-portal.fullname" . }}
  labels:
    app: {{ template "apollo-portal.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  application-github.properties: |-
    # DataSource
    spring.datasource.url = {{ .Values.env.url }}
    spring.datasource.username = {{ .Values.env.username }}
    spring.datasource.password = {{ .Values.env.password }}
  apollo-env.properties: |-
    qa.meta={{ .Values.env.qa_meta }}
    qa2.meta={{ .Values.env.qa2_meta }}
    online.meta={{ .Values.env.online_meta }}
